baseURL = 'https://blog.gil.lol'
copyright = "{year} Gil Poiares Oliveira" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-GB'
defaultContentLanguage = 'en'
theme = 'gilsblog'
title = "Gil's Blog"
enableRobotsTXT = true
summaryLength = 15
paginate = 5


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
noHl = false
style = 'dracula'
tabWidth = 4
