[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = 2

[[main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 3

# Social Media Configuration

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://social.lol/@gil"
weight = 1
