name = "Gil's Blog Theme"
# license = "MIT"
version = "0.0.1"
# licenselink = "https://github.com/jacksalici/salinger/blob/master/LICENSE"
# description = "Salinger is a clean, minimalistic, mobile-first, blazing-fast, fancy and lightweight theme for the Hugo framework built with TailwindCSS and DaisyUI"
# homepage = "https://github.com/jacksalici/salinger-theme/"
# tags = ["simple", "minimal", "clean", "fast", "blog", "portfolio", "responsive", "twemoji", "recursion", "section", "tailwind", "daisyui"]
# features = ["fast", "blog", "sorting", "dark mode", "categories", "tailwind", "seo"]
# min_version = "0.112.0"

[author]
  name = "Gil Poiares-Oliveira"
  homepage = "giloliveira.net"



